import type { Metadata } from "next";
import "@/style/globals.css";
import { Poppins, Roboto } from "next/font/google";
import Navbar from "@/Components/Navbar";
export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "300", "500", "700"],
});
export const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "400", "500", "700"],
  style: ["italic", "normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
